# We deliberately don't use travis's language=python option because
# we install miniconda and use conda to get python. Additionally,
# Travis's auto-install of python doesn't work on osx images (see
# https://github.com/travis-ci/travis-ci/issues/4729).
language: generic
sudo: false
os:
  - linux
arch: 
  - arm64
addons:
  firefox: latest

env:
  global:
    - PYENV_VERSION=3.6
    - CHANS_DEV="-c pyviz/label/dev"
    - CHANS="-c pyviz"

stages:
  - test_pyviz_comms
  - test_jlab
  - name: conda_dev_package
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
  - name: pip_dev_package
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
  - name: conda_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$
  - name: pip_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$

jobs:
  include:
    ########## DEVELOPER INSTALL ##########

    - &default
      stage: test_pyviz_comms
      env: DESC="dev test_flakes"
      before_install:
        - sudo pip install pyctdev
        - wget "https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh" -O archiconda.sh
        - chmod +x archiconda.sh
        - bash archiconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        - sudo ln -s $HOME/miniconda/bin/conda /usr/bin/
        - sudo doit ecosystem_setup
      install:
        - sudo conda create -n test-environment python=$PYTHON_VERSION
        - source activate test-environment
        - sudo apt-get install libjpeg-dev zlib1g-dev
        - sudo rm -f /usr/bin/python && sudo ln -s $HOME/miniconda/envs/test-environment/bin/python /usr/bin/python 
        - sudo conda install conda
        - pip install --user "pyctdev>=0.5" "certifi==2019.11.28" "pip==19.3.1" "setuptools==42.0.2" "wheel==0.33.6" doit
        - sudo conda install "ca-certificates==2018.03.07" "libffi==3.2.1" "libgcc-ng==7.3.0" "libstdcxx-ng==7.3.0" "ncurses==6.1" "openssl==1.1.1d" "python==3.6.7" "readline==8.0" "sqlite==3.30.1" "tk==8.6.10" "xz==5.2.4" "zlib==1.2.11" "conda==4.8.0" "cycler==0.10.0" "expat==2.2.6" "freetype==2.9.1" "glob2==0.7" "gmp==6.1.2" "kiwisolver==1.1.0" "libsodium==1.0.16" "libtiff==4.1.0" "pandas==0.25.3" - sudo pip install "bokeh >=1.0.0" "colorcet >=2" "holoviews >=1.11.0" "coveralls" "nose" "flake8" "parameterized" "pytest" "nbsmoke >=0.2.0" "coveralls" "nose" "flake8" "parameterized" "pytest" "nbsmoke >=0.2.0" "param>=1.7.0" "pyct>=0.4.4" "setuptools>=30.3.0" 
        - sudo doit env_capture
        - sudo python setup.py install
        - sudo ln -s /home/travis/miniconda/envs/test-environment/bin/nosetests /usr/bin/nosetests
      script: doit test_flakes

    - stage: test_jlab
      before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start || true
        - pip install pyctdev && doit miniconda_install && pip uninstall -y doit pyctdev
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        - conda install -c pyviz "pyctdev>=0.5" && doit ecosystem_setup
      install:
        - doit env_create $CHANS_DEV --python=$PYENV_VERSION
        - source activate test-environment
        - conda install nodejs notebook selenium
        - pip install --pre jupyterlab
      script:
        - npm install
        - npm run build
        - jupyter labextension install .
        - jupyter lab clean
        - jupyter labextension link .
        - python -m jupyterlab.selenium_check

    ########## END-USER PACKAGES ##########

    ### CONDA ####

    - <<: *default
      stage: conda_dev_package
      env: DESC="" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit package_build $CHANS_DEV --no-pkg-tests
      script:
        - doit package_upload --token=$ANACONDA_TOKEN --label=dev

    - <<: *default
      stage: conda_package
      env: DESC="" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit package_build $CHANS --no-pkg-tests
      script:
        - doit package_upload --token=$ANACONDA_TOKEN --label=dev --label=main

    ### PyPI ###

    - <<: *default
      stage: pip_dev_package
      env: PYPI="https://test.pypi.org/legacy/" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit develop_install $CHANS_DEV -o tests && pip uninstall -y pyviz_comms
        - doit pip_on_conda
        - doit ecosystem=pip package_build --no-pkg-tests
      script: doit ecosystem=pip package_upload -u $TPPU -p $TPPP -r ${PYPI}

    - <<: *default
      stage: pip_package
      env: PYPI="https://upload.pypi.org/legacy/" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit develop_install $CHANS_DEV -o tests && pip uninstall -y pyviz_comms
        - doit pip_on_conda
        - doit ecosystem=pip package_build --no-pkg-tests
      script: doit ecosystem=pip package_upload -u $PPU -p $PPP -r ${PYPI}
