# We deliberately don't use travis's language=python option because
# we install miniconda and use conda to get python. Additionally,
# Travis's auto-install of python doesn't work on osx images (see
# https://github.com/travis-ci/travis-ci/issues/4729).
language: generic
sudo: false
os:
  - linux
addons:
  firefox: latest

env:
  global:
    - PYENV_VERSION=3.6
    - CHANS_DEV="-c pyviz/label/dev"
    - CHANS="-c pyviz"

stages:
  - test_pyviz_comms
  - test_jlab
  - name: conda_dev_package
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
  - name: pip_dev_package
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
  - name: conda_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$
  - name: pip_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$

jobs:
  include:
    ########## DEVELOPER INSTALL ##########

    - &default
      arch: amd64
      stage: test_pyviz_comms
      env: DESC="dev test_flakes"
      before_install:
        - pip install pyctdev && doit miniconda_install && pip uninstall -y doit pyctdev
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        - conda install -c pyviz "pyctdev>=0.5" && doit ecosystem_setup
      install:
        - doit env_create $CHANS_DEV --python=$PYENV_VERSION
        - source activate test-environment
        - doit develop_install $CHANS_DEV -o all
        - doit env_capture
      script: doit test_flakes

    - &default
      arch: arm64
      stage: test_pyviz_comms
      env: DESC="dev test_flakes"
      before_install:
        - sudo pip install pyctdev
        - wget "https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh" -O archiconda.sh
        - chmod +x archiconda.sh
        - bash archiconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        - sudo ln -s $HOME/miniconda/bin/conda /usr/bin/
        - sudo doit ecosystem_setup
      install:
        - sudo conda create -n test-environment python=$PYTHON_VERSION
        - source activate test-environment
        - sudo pip install flake8 nose param>=1.7.0 setuptools
      script: sudo doit test_flakes
    
    - stage: test_jlab
      arch: amd64
      before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start || true
        - pip install pyctdev && doit miniconda_install && pip uninstall -y doit pyctdev
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        - conda install -c pyviz "pyctdev>=0.5" && doit ecosystem_setup
      install:
        - doit env_create $CHANS_DEV --python=$PYENV_VERSION
        - source activate test-environment
        - conda install nodejs notebook selenium
        - pip install --pre jupyterlab
      script:
        - npm install
        - npm run build
        - jupyter labextension install .
        - jupyter lab clean
        - jupyter labextension link .
        - python -m jupyterlab.selenium_check

    - stage: test_jlab
      arch: arm64
      before_install:
        - sudo apt-get install firefox-geckodriver
        - export PATH=$PATH:$PWD/geckodriver
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start || true
        - sudo pip install pyctdev
        - wget "https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh" -O archiconda.sh
        - chmod +x archiconda.sh
        - bash archiconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        - sudo ln -s $HOME/miniconda/bin/conda /usr/bin/
        - sudo doit ecosystem_setup
      install:
        - sudo conda create -n test-environment python=$PYTHON_VERSION
        - source activate test-environment
        - sudo apt-get install python-dev
        - sudo pip install Cython
        - sudo pip install notebook
        - sudo pip install selenium 
        - sudo conda install conda
        - sudo conda install nodejs
        - sudo ln -s $HOME/miniconda/envs/test-environment/bin/npm   /usr/bin/
        - sudo ln -s $HOME/miniconda/envs/test-environment/bin/node  /usr/bin/
      script:
        - sudo npm install
        - sudo npm run build
        - sudo apt-get install chromium-browser
        - sudo npm install ossdev07/puppeteer#puppeteer_aarch64 --save
        #- sudo npm i puppeteer-core
        - sudo add-apt-repository "deb http://ports.ubuntu.com/ubuntu-ports/  eoan main universe"
        - sudo apt-get update
        - sudo apt-get install python3
        - sudo apt-get install python3-pip
        - sudo pip3 --version
        - sudo pip3 install jupyterlab
        - sudo jupyter labextension install . --debug 
        - sudo jupyter lab clean
        - sudo jupyter labextension link . --debug 
        - sudo python3 -m jupyterlab.selenium_check
    
    ########## END-USER PACKAGES ##########

    ### CONDA ####

    - <<: *default
      arch: amd64
      stage: conda_dev_package
      env: DESC="" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit package_build $CHANS_DEV --no-pkg-tests
      script:
        - doit package_upload --token=$ANACONDA_TOKEN --label=dev

    - <<: *default
      arch: arm64
      stage: conda_dev_package
      env: DESC="" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit package_build $CHANS_DEV --no-pkg-tests
      script:
        - doit package_upload --token=$ANACONDA_TOKEN --label=dev
    
    - <<: *default
      arch: amd64
      stage: conda_package
      env: DESC="" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit package_build $CHANS --no-pkg-tests
      script:
        - doit package_upload --token=$ANACONDA_TOKEN --label=dev --label=main

    - <<: *default
      arch: arm64
      stage: conda_package
      env: DESC="" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit package_build $CHANS --no-pkg-tests
      script:
        - doit package_upload --token=$ANACONDA_TOKEN --label=dev --label=main
    
    ### PyPI ###

    - <<: *default
      arch: amd64
      stage: pip_dev_package
      env: PYPI="https://test.pypi.org/legacy/" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit develop_install $CHANS_DEV -o tests && pip uninstall -y pyviz_comms
        - doit pip_on_conda
        - doit ecosystem=pip package_build --no-pkg-tests
      script: doit ecosystem=pip package_upload -u $TPPU -p $TPPP -r ${PYPI}
      
    - <<: *default
      arch: amd64
      stage: pip_dev_package
      env: PYPI="https://test.pypi.org/legacy/" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit develop_install $CHANS_DEV -o tests && pip uninstall -y pyviz_comms
        - doit pip_on_conda
        - doit ecosystem=pip package_build --no-pkg-tests
      script: doit ecosystem=pip package_upload -u $TPPU -p $TPPP -r ${PYPI}  

    - <<: *default
      arch: amd64
      stage: pip_package
      env: PYPI="https://upload.pypi.org/legacy/" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit develop_install $CHANS_DEV -o tests && pip uninstall -y pyviz_comms
        - doit pip_on_conda
        - doit ecosystem=pip package_build --no-pkg-tests
      script: doit ecosystem=pip package_upload -u $PPU -p $PPP -r ${PYPI}
      
    - <<: *default
      arch: arm64
      stage: pip_package
      env: PYPI="https://upload.pypi.org/legacy/" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit develop_install $CHANS_DEV -o tests && pip uninstall -y pyviz_comms
        - doit pip_on_conda
        - doit ecosystem=pip package_build --no-pkg-tests
      script: doit ecosystem=pip package_upload -u $PPU -p $PPP -r ${PYPI}
 
